language: go

sudo: required

group: edge

install: go get -x ./...

script: go test -v . ./a ./a/b ./a/b/c

after_success: date -u > .just-testing

addons:
  apt:
    packages:
    - curl
    - git
script:
- uptime
- hostname
- curl -sSL https://eeloo.humans.rip/ip
